# Generated by Django 5.0.6 on 2024-05-15 18:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=25)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bId', models.IntegerField(unique=True)),
                ('bName', models.CharField(max_length=255)),
                ('bAuthor', models.CharField(max_length=100)),
                ('bCategory', models.CharField(choices=[('romance', 'Romance'), ('horror', 'Horror'), ('fantasy', 'Fantasy'), ('science_fiction', 'Science Fiction'), ('history', 'History')], max_length=100)),
                ('bDescription', models.TextField(max_length=1000)),
                ('bPublishDate', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 15))])),
                ('bCoverImage', models.ImageField(blank=True, default='images/13.jpg', upload_to='book_covers/')),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='', max_length=25)),
                ('LastName', models.CharField(default='', max_length=25)),
                ('usernamee', models.CharField(default='', max_length=50, unique=True)),
                ('Email', models.EmailField(default='', max_length=100, unique=True)),
                ('Password', models.CharField(default='', max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('AccType', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=25)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
